/**
 * TranslatedTextPanel.tsx
 *
 * A collapsible panel that displays the entire translated document as Markdown.
 * The content is rendered in read-only format, allowing users to review the translation.
 * Translations are added to the panel as the user translates it.
 *
 * Props:
 * - `translationEditorValue`: A string containing the full translated text,
 *    typically generated by joining individual chunk translations with a delimiter.
 *
 * Behavior:
 * - Clicking the panel header toggles visibility of the translated content.
 * - The content is scrollable and formatted using Markdown styling.
 */

import { useState } from 'react';
import MDEditor from '@uiw/react-md-editor';
import ButtonHelp from '../general/ButtonHelp';

interface TranslatedTextPanelProps {
  translationEditorValue: string;
}

export default function TranslatedTextPanel({ translationEditorValue }: TranslatedTextPanelProps) {
  const [showTranslated, setShowTranslated] = useState(false);

  return (
    <section className="flex flex-col justify-center items-center w-full bg-white cursor-pointer hover:bg-gray-100 mt-10">
      <div
        className="w-full flex justify-between py-3 px-4 bg-white hover:bg-gray-100 border-b border-gray-300"
        onClick={() => setShowTranslated(!showTranslated)}
      >
        <h3 className="text-xl select-none">Translated text</h3>
        <ButtonHelp tooltipText="Here you can see the entire document translated and review the final result as a whole." />
      </div>

      {showTranslated && (
        <div className="p-3 w-full">
          <MDEditor.Markdown
            className="whitespace-pre-wrap px-2 py-1 w-full overflow-y-auto max-h-[450px]"
            source={translationEditorValue}
          />
        </div>
      )}
    </section>
  );
}
