/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as TranslationsImport } from './routes/translations';
import { Route as SettingsImport } from './routes/settings';
import { Route as LoginImport } from './routes/login';
import { Route as DevLoadingImport } from './routes/devLoading';
import { Route as DeeplFileTranslateImport } from './routes/deeplFileTranslate';
import { Route as AuthImport } from './routes/_auth';
import { Route as IndexImport } from './routes/index';
import { Route as TranslateIndexImport } from './routes/translate/index';
import { Route as AuthProfileImport } from './routes/_auth.profile';
import { Route as TranslateDocIdIndexImport } from './routes/translate/$docId/index';
import { Route as TranslateDocIdCompletedScreenImport } from './routes/translate/$docId/completedScreen';
import { Route as TranslateDocIdAutoTranslateImport } from './routes/translate/$docId/autoTranslate';

// Create/Update Routes

const TranslationsRoute = TranslationsImport.update({
  id: '/translations',
  path: '/translations',
  getParentRoute: () => rootRoute,
} as any);

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any);

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any);

const DevLoadingRoute = DevLoadingImport.update({
  id: '/devLoading',
  path: '/devLoading',
  getParentRoute: () => rootRoute,
} as any);

const DeeplFileTranslateRoute = DeeplFileTranslateImport.update({
  id: '/deeplFileTranslate',
  path: '/deeplFileTranslate',
  getParentRoute: () => rootRoute,
} as any);

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const TranslateIndexRoute = TranslateIndexImport.update({
  id: '/translate/',
  path: '/translate/',
  getParentRoute: () => rootRoute,
} as any);

const AuthProfileRoute = AuthProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any);

const TranslateDocIdIndexRoute = TranslateDocIdIndexImport.update({
  id: '/translate/$docId/',
  path: '/translate/$docId/',
  getParentRoute: () => rootRoute,
} as any);

const TranslateDocIdCompletedScreenRoute = TranslateDocIdCompletedScreenImport.update({
  id: '/translate/$docId/completedScreen',
  path: '/translate/$docId/completedScreen',
  getParentRoute: () => rootRoute,
} as any);

const TranslateDocIdAutoTranslateRoute = TranslateDocIdAutoTranslateImport.update({
  id: '/translate/$docId/autoTranslate',
  path: '/translate/$docId/autoTranslate',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/_auth': {
      id: '/_auth';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof AuthImport;
      parentRoute: typeof rootRoute;
    };
    '/deeplFileTranslate': {
      id: '/deeplFileTranslate';
      path: '/deeplFileTranslate';
      fullPath: '/deeplFileTranslate';
      preLoaderRoute: typeof DeeplFileTranslateImport;
      parentRoute: typeof rootRoute;
    };
    '/devLoading': {
      id: '/devLoading';
      path: '/devLoading';
      fullPath: '/devLoading';
      preLoaderRoute: typeof DevLoadingImport;
      parentRoute: typeof rootRoute;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    '/settings': {
      id: '/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof SettingsImport;
      parentRoute: typeof rootRoute;
    };
    '/translations': {
      id: '/translations';
      path: '/translations';
      fullPath: '/translations';
      preLoaderRoute: typeof TranslationsImport;
      parentRoute: typeof rootRoute;
    };
    '/_auth/profile': {
      id: '/_auth/profile';
      path: '/profile';
      fullPath: '/profile';
      preLoaderRoute: typeof AuthProfileImport;
      parentRoute: typeof AuthImport;
    };
    '/translate/': {
      id: '/translate/';
      path: '/translate';
      fullPath: '/translate';
      preLoaderRoute: typeof TranslateIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/translate/$docId/autoTranslate': {
      id: '/translate/$docId/autoTranslate';
      path: '/translate/$docId/autoTranslate';
      fullPath: '/translate/$docId/autoTranslate';
      preLoaderRoute: typeof TranslateDocIdAutoTranslateImport;
      parentRoute: typeof rootRoute;
    };
    '/translate/$docId/completedScreen': {
      id: '/translate/$docId/completedScreen';
      path: '/translate/$docId/completedScreen';
      fullPath: '/translate/$docId/completedScreen';
      preLoaderRoute: typeof TranslateDocIdCompletedScreenImport;
      parentRoute: typeof rootRoute;
    };
    '/translate/$docId/': {
      id: '/translate/$docId/';
      path: '/translate/$docId';
      fullPath: '/translate/$docId';
      preLoaderRoute: typeof TranslateDocIdIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthProfileRoute: typeof AuthProfileRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthProfileRoute: AuthProfileRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '': typeof AuthRouteWithChildren;
  '/deeplFileTranslate': typeof DeeplFileTranslateRoute;
  '/devLoading': typeof DevLoadingRoute;
  '/login': typeof LoginRoute;
  '/settings': typeof SettingsRoute;
  '/translations': typeof TranslationsRoute;
  '/profile': typeof AuthProfileRoute;
  '/translate': typeof TranslateIndexRoute;
  '/translate/$docId/autoTranslate': typeof TranslateDocIdAutoTranslateRoute;
  '/translate/$docId/completedScreen': typeof TranslateDocIdCompletedScreenRoute;
  '/translate/$docId': typeof TranslateDocIdIndexRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '': typeof AuthRouteWithChildren;
  '/deeplFileTranslate': typeof DeeplFileTranslateRoute;
  '/devLoading': typeof DevLoadingRoute;
  '/login': typeof LoginRoute;
  '/settings': typeof SettingsRoute;
  '/translations': typeof TranslationsRoute;
  '/profile': typeof AuthProfileRoute;
  '/translate': typeof TranslateIndexRoute;
  '/translate/$docId/autoTranslate': typeof TranslateDocIdAutoTranslateRoute;
  '/translate/$docId/completedScreen': typeof TranslateDocIdCompletedScreenRoute;
  '/translate/$docId': typeof TranslateDocIdIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/_auth': typeof AuthRouteWithChildren;
  '/deeplFileTranslate': typeof DeeplFileTranslateRoute;
  '/devLoading': typeof DevLoadingRoute;
  '/login': typeof LoginRoute;
  '/settings': typeof SettingsRoute;
  '/translations': typeof TranslationsRoute;
  '/_auth/profile': typeof AuthProfileRoute;
  '/translate/': typeof TranslateIndexRoute;
  '/translate/$docId/autoTranslate': typeof TranslateDocIdAutoTranslateRoute;
  '/translate/$docId/completedScreen': typeof TranslateDocIdCompletedScreenRoute;
  '/translate/$docId/': typeof TranslateDocIdIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | ''
    | '/deeplFileTranslate'
    | '/devLoading'
    | '/login'
    | '/settings'
    | '/translations'
    | '/profile'
    | '/translate'
    | '/translate/$docId/autoTranslate'
    | '/translate/$docId/completedScreen'
    | '/translate/$docId';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | ''
    | '/deeplFileTranslate'
    | '/devLoading'
    | '/login'
    | '/settings'
    | '/translations'
    | '/profile'
    | '/translate'
    | '/translate/$docId/autoTranslate'
    | '/translate/$docId/completedScreen'
    | '/translate/$docId';
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/deeplFileTranslate'
    | '/devLoading'
    | '/login'
    | '/settings'
    | '/translations'
    | '/_auth/profile'
    | '/translate/'
    | '/translate/$docId/autoTranslate'
    | '/translate/$docId/completedScreen'
    | '/translate/$docId/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRoute: typeof AuthRouteWithChildren;
  DeeplFileTranslateRoute: typeof DeeplFileTranslateRoute;
  DevLoadingRoute: typeof DevLoadingRoute;
  LoginRoute: typeof LoginRoute;
  SettingsRoute: typeof SettingsRoute;
  TranslationsRoute: typeof TranslationsRoute;
  TranslateIndexRoute: typeof TranslateIndexRoute;
  TranslateDocIdAutoTranslateRoute: typeof TranslateDocIdAutoTranslateRoute;
  TranslateDocIdCompletedScreenRoute: typeof TranslateDocIdCompletedScreenRoute;
  TranslateDocIdIndexRoute: typeof TranslateDocIdIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DeeplFileTranslateRoute: DeeplFileTranslateRoute,
  DevLoadingRoute: DevLoadingRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  TranslationsRoute: TranslationsRoute,
  TranslateIndexRoute: TranslateIndexRoute,
  TranslateDocIdAutoTranslateRoute: TranslateDocIdAutoTranslateRoute,
  TranslateDocIdCompletedScreenRoute: TranslateDocIdCompletedScreenRoute,
  TranslateDocIdIndexRoute: TranslateDocIdIndexRoute,
};

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/deeplFileTranslate",
        "/devLoading",
        "/login",
        "/settings",
        "/translations",
        "/translate/",
        "/translate/$docId/autoTranslate",
        "/translate/$docId/completedScreen",
        "/translate/$docId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/profile"
      ]
    },
    "/deeplFileTranslate": {
      "filePath": "deeplFileTranslate.tsx"
    },
    "/devLoading": {
      "filePath": "devLoading.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/translations": {
      "filePath": "translations.tsx"
    },
    "/_auth/profile": {
      "filePath": "_auth.profile.tsx",
      "parent": "/_auth"
    },
    "/translate/": {
      "filePath": "translate/index.tsx"
    },
    "/translate/$docId/autoTranslate": {
      "filePath": "translate/$docId/autoTranslate.tsx"
    },
    "/translate/$docId/completedScreen": {
      "filePath": "translate/$docId/completedScreen.tsx"
    },
    "/translate/$docId/": {
      "filePath": "translate/$docId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
